version: "3.9"

services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: profile_db
      CORS_ORIGIN: http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001
      SEED_PROFILES_SOURCE: https://drive.google.com/uc?export=download&id=1Up06dcS9OfUEnDj_u6OV_xTRntupFhPH
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
